# Generated by Django 2.1.5 on 2019-02-07 15:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='video_url',
            field=models.TextField(default='https://www.youtube.com/watch?v=QohH89Eu5iM', validators=[django.core.validators.URLValidator()]),
        ),
    ]
