# Generated by Django 2.1.5 on 2019-02-07 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190207_2018'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='rcons',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Cons'),
        ),
        migrations.AddField(
            model_name='review',
            name='rpros',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.RPros'),
        ),
    ]
