# Generated by Django 2.1.5 on 2019-02-07 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190207_2023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='rpros',
        ),
        migrations.AddField(
            model_name='review',
            name='rpros',
            field=models.ManyToManyField(to='blog.RPros'),
        ),
    ]
