# Generated by Django 2.1.5 on 2019-02-07 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20190207_2025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='rcons',
        ),
        migrations.AddField(
            model_name='review',
            name='rcons',
            field=models.ManyToManyField(to='blog.Cons'),
        ),
    ]
