# Generated by Django 2.1.5 on 2019-02-07 16:28

import django.core.validators
from django.db import migrations, models
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20190207_2026'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='comfort',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='review',
            name='video_url',
            field=embed_video.fields.EmbedVideoField(default='https://www.youtube.com/watch?v=QohH89Eu5iM'),
        ),
    ]
